### ISSUE TITLE
Solo funciona el comando $ rae -p

### ISSUE THREAD

**Issue by my-andrea** [sardach/rae-cli#1]
Hi, preguntaba si este valioso script está actualizado, funciona o existe alguna restricción que desconozca. De momento solo funciona el comando `$ rae -p` que arroja la `palabra del día` Gracias.

**Comment by leoalvarezg** [comment]
Tengo exactamente el mismo problema.

**Comment by jacob-mf** [comment]
> Tengo exactamente el mismo problema.

Saludos, @my-andrea @leoalvarezg @sardach 
He reutilizado/cambiado el código y por ahora funciona en nueva versión aquí:
<https://github.com/jacob-mf/drae>
 <https://gitlab.com/caldez/drae>
 <https://libregit.org/caldez/drae>
Espero les pueda servir de ayuda.
Mis agradecimientos y admiración a @sardach , su código fue la principal inspiración, juntoa otra aplicación antigua, tambi´en llamada drae, que dejo de funcionar hace mucho. ¡Salud!

**Comment by sardach** [comment]
Hola @my-andrea, @leoalvarez 
Lamento responder con tanta demora, intentaré mirar mis notificaciones de GitHub más seguido.
Por el momento el script funciona de nuevo y procuraré que siga así :)

@jacob-mf 
Me halaga mucho que hayas usado rae-cli como inspiración para tu proyecto. Lo enlazare en el readme 

Saludos y suerte a todos.
